// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ8BLv4BosBnAa0hbZd3XqsgrtesKVtDE',
    appId: '1:554852653704:web:25fd0fc2a5e455814b5d3d',
    messagingSenderId: '554852653704',
    projectId: 'ciftciden-8636d',
    authDomain: 'ciftciden-8636d.firebaseapp.com',
    storageBucket: 'ciftciden-8636d.appspot.com',
    measurementId: 'G-539R7LT5BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS3mVp_CjJu-HCJ3u5jbV5hq3_dX-bHiE',
    appId: '1:554852653704:android:bd8956024e6af7fe4b5d3d',
    messagingSenderId: '554852653704',
    projectId: 'ciftciden-8636d',
    storageBucket: 'ciftciden-8636d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyeR-1Y4_sJIJK7azh01CjhrZ-T44GlKQ',
    appId: '1:554852653704:ios:9c9cb06b2f1366a04b5d3d',
    messagingSenderId: '554852653704',
    projectId: 'ciftciden-8636d',
    storageBucket: 'ciftciden-8636d.appspot.com',
    iosClientId: '554852653704-flh5l9gleu6vgu3ru3249m3t9ec20qfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ciftciden',
  );
}
